<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;
use AppBundle\Entity\Invoice;

/**
 * InvoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByPage($page = 1)
    {
        $query = $this->createQueryBuilder('invoice')
            ->getQuery()
            ->setFirstResult(($page-1) * Invoice::PER_PAGE)
            ->setMaxResults(Invoice::PER_PAGE);

        return new Paginator($query, $fetchJoinCollection = true);
    }

    public function nbPages() {
        return ceil(count($this->getByPage()) / Invoice::PER_PAGE) || 1;
    }
}
