<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;
use AppBundle\Entity\Product;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByPage($page = 1)
    {
        $query = $this->createQueryBuilder('product')
            ->getQuery()
            ->setFirstResult(($page-1) * Product::PER_PAGE)
            ->setMaxResults(Product::PER_PAGE);

        return new Paginator($query, $fetchJoinCollection = true);
    }

    public function nbPages() {
        $nbPages = ceil(count($this->getByPage()) / Product::PER_PAGE);
        return ($nbPages === 0) ? 1 : $nbPages;
    }
}
