simplon_blog:
    resource: "@SimplonBlogBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

categories:
    resource: AppBundle\Controller\CategoryController
    type:     rest